baseURL = "http://www.gustavjwlundberg.com/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Gustav JW Lundberg"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifer for a menu item
    identifier = "Experience"

    url = "/work_experience/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Work Experience"

    # Weights are used to determine the ordering
    weight = 1

	[[menu.main]]
    identifier = "Skills"
	name = "Skills"
    url = "/skills/"
    weight = 2

  [[menu.main]]
    identifier = "Education"
    name = "Education"
    url = "/education/"
    weight = 3
    
  [[menu.main]]
    identifier = "Resume"
	name = "Resume"
    url = "/resume/"
    weight = 4
	
[params]
  avatarURL = "/images/avatar.png"
  description = "I am a data analysist based in the New York Metropoolitan Area. I utilize methods from pyschology, neuroscience, and quantitative pscyhology to help clients answer applied questions."
  
    socialIcons = [
	{name = "gmail", url = "mailto:gustavjwlundberg@gmail.com"},
	{name = "github", url = "https://github.com/gustavjwlundberg"},
	{name = "twitter", url = "https://twitter.com/gjwlundberg"}
  ]